[IMG ID]
ID=60847001
Name=geokrety.org
Elevation=M
Preprocess=F
CodePage=1250
LblCoding=9
TreSize=1138
TreMargin=0.00000
RgnLimit=1024
Transparent=Y
POIIndex=Y
POIOnly=Y
Levels=3
Level0=20
Level1=17
Level2=10
Zoom0=0
Zoom1=1
Zoom2=2
[END-IMG ID]



[POI]
Type=0x6604
Label=Pago Pago (AS)
Data0=(14.27806,9.2975)
EndLevel=1
[END]
[POI]
Type=0x6604
Label=Nuku`alofa (TO)
Data0=(21.1333333,4.8)
EndLevel=1
[END]
[POI]
Type=0x6604
Label=Apia (WS)
Data0=(13.8333333,8.2666667)
EndLevel=1
[END]



